# Generated by Django 3.0.8 on 2020-07-04 10:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dzial', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GrupaRobocza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=15)),
                ('aktywna', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=15)),
                ('aktywna', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Narzedzia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupa', models.CharField(max_length=15)),
                ('uwagi', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rozciagi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_zlecenia', models.CharField(max_length=10)),
                ('nr_pozycji', models.DecimalField(decimal_places=0, max_digits=4)),
                ('nr_pracownika', models.DecimalField(decimal_places=0, max_digits=5)),
                ('rozciag', models.DecimalField(decimal_places=0, max_digits=5)),
                ('przekroj_przewodu', models.DecimalField(decimal_places=2, max_digits=4)),
                ('indeks_kontaktu', models.CharField(max_length=10)),
                ('poprawkowe', models.BooleanField(default=False)),
                ('narzedzia', models.CharField(max_length=20)),
                ('data_dodania', models.DateTimeField(default=datetime.datetime(2020, 7, 4, 12, 51, 32, 904125), verbose_name='data dodania')),
                ('potwierdzenie', models.BooleanField(default=False)),
                ('komputer_user', models.CharField(default='mirek', max_length=10)),
                ('komputer', models.CharField(default='Mirek-PC', max_length=30)),
                ('grupa_robocza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rozciag.GrupaRobocza')),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rozciag.Lista')),
                ('narzedzia_rodzaj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rozciag.Narzedzia')),
                ('zalogowany_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rozciag.Author')),
            ],
        ),
    ]
