# Generated by Django 3.0.8 on 2020-07-04 13:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rozciag', '0002_auto_20200704_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='rozciagi',
            name='lista',
            field=models.CharField(choices=[('lista', 'Lista połączeń'), ('zlecenie', 'Zlecenie')], default='lista', max_length=15),
        ),
        migrations.AlterField(
            model_name='rozciagi',
            name='data_dodania',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 4, 15, 5, 14, 221713), verbose_name='data dodania'),
        ),
    ]
