# Generated by Django 3.0.8 on 2020-07-04 14:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rozciag', '0003_auto_20200704_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='narzedzia',
            name='aktywny',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='rozciagi',
            name='data_dodania',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 4, 16, 13, 55, 227630), verbose_name='data dodania'),
        ),
        migrations.AlterField(
            model_name='rozciagi',
            name='lista',
            field=models.CharField(choices=[('lista', 'Lista połączeń'), ('zlecenie', 'Zlecenie produkcyjne')], default='lista', max_length=15),
        ),
    ]
