# Generated by Django 3.0.8 on 2020-07-29 18:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rozciag', '0004_auto_20200704_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rozciagi',
            name='data_dodania',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='data dodania'),
        ),
        migrations.AlterField(
            model_name='rozciagi',
            name='nr_pozycji',
            field=models.CharField(max_length=20),
        ),
    ]
