# Generated by Django 3.0.8 on 2020-08-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rozciag', '0005_auto_20200729_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rozciagi',
            name='nr_pozycji',
            field=models.CharField(max_length=200),
        ),
    ]
