# Generated by Django 3.0.8 on 2020-10-13 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rozciag', '0006_auto_20200806_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='rozciagi',
            name='wysokosc',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
