# Generated by Django 3.0.8 on 2020-10-13 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rozciag', '0007_rozciagi_wysokosc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rozciagi',
            name='wysokosc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
