# Generated by Django 3.0.8 on 2020-10-13 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rozciag', '0008_auto_20201013_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rozciagi',
            name='wysokosc',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True),
        ),
    ]
